apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: nvidia-nim-llama3-8b-instruct-1.0.0
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8000'
  containers:
    - env:
        - name: NIM_CACHE_PATH
          value: /mnt/models/cache
        - name: NGC_API_KEY
          valueFrom:
            secretKeyRef:
              key: NGC_API_KEY
              name: nvidia-nim-secrets
      image: 'nvcr.io/nim/meta/llama3-8b-instruct:1.0.0'
      name: kserve-container
      ports:
        - containerPort: 8000
          protocol: TCP
      resources:
        limits:
          cpu: '12'
          memory: 256Gi
        requests:
          cpu: '12'
          memory: 128Gi
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /mnt/models/cache
          name: nim-pvc
  imagePullSecrets:
    - name: ngc-secret
  protocolVersions:
    - v2
    - grpc-v2
  supportedModelFormats:
    - autoSelect: true
      name: nvidia-nim-llama3-8b-instruct
      priority: 1
      version: '1.1.0'
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 16Gi
      name: dshm
    - name: nim-pvc
      persistentVolumeClaim:
        claimName: nim-pvc
